# ** Default values of all configuration are written in**
#  https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
#
# Detail examples of each configuration are
#  https://rubocop.readthedocs.io/en/latest/cops_layout
#
# General guide-line is
#  https://github.com/rubocop-hq/ruby-style-guide

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/EndAlignment:
  Enabled: true
  AutoCorrect: true

Layout/LineLength:
  Enabled: true
  AutoCorrect: false
  Max: 120

Metrics/BlockLength:
  Enabled: true
  Max: 30
  ExcludedMethods: ['describe', 'context']

Metrics/MethodLength:
  Enabled: true
  Max: 30
